kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "wireguard.configMapNameConf" . }}
data:
  wg0.conf: |
    [Interface]
    Address = 10.0.0.2/32
    ListenPort = 51820
    PostUp = wg set wg0 private-key /etc/wireguard/privatekey; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    DNS = 1.1.1.1,192.168.10.1

    [Peer]
    # Name = vps
    PublicKey = {{ .Values.wgConfig.serverPublicKey }}
    AllowedIPs = 10.0.0.0/24
    Endpoint = {{ .Values.wgConfig.serverIp }}:{{ .Values.wgConfig.serverPort }}
    PersistentKeepalive = 15
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "wireguard.configMapNameScript" . }}
data:
  entrypoint.sh: |
    #!/bin/bash

    finish () {
        wg-quick down wg0
        exit 0
    }
    trap finish SIGTERM SIGINT SIGQUIT

    wg-quick up /etc/wireguard/wg0.conf

    sleep 10

    ping -4 -w 10 10.0.0.1

    # Inifinite sleep
    while true; do
        sleep 86400
        wait $!
    done
