- name: Configure Wireguard
  hosts: wireguard
  tasks:
  - name: Print message to check connection
    ansible.builtin.debug:
      msg: Hello world
  - name: Install packages
    ansible.builtin.apt:
      name:
      - wireguard
      - net-tools
      - qrencode
      update_cache: yes
  - name: Install dsnet
    ansible.builtin.shell: |
      if ! (which dsnet)
      then
        sudo wget https://github.com/naggie/dsnet/releases/latest/download/dsnet-linux-amd64 -O /usr/local/bin/dsnet
        sudo chmod +x /usr/local/bin/dsnet
      else
        echo ...skip...dsnet already installed.
      fi
  - name: Create dsnet config
    ansible.builtin.copy:
      dest: /etc/dsnetconfig.json
      content: "{{ lookup('community.sops.sops', 'dsnetconfig.enc.json') }}"
  - name: Enable IP forward in file
    ansible.builtin.lineinfile:
      path: /etc/sysctl.conf
      regexp: '^net.ipv4.ip_forward='
      line: net.ipv4.ip_forward=1
  - name: Check ip forward
    ansible.builtin.shell: sysctl -p
  - name: Start wireguard
    ansible.builtin.shell: |
      if ! (dsnet report)
      then
        dsnet up
      else
        echo ...skip...dsnet is running
      fi
    register: results
  - debug:
      var: results.stdout
  - name: Copy email template
    ansible.builtin.copy:
      src: email_template.json
      dest: /home/email_template.json
  - name: Copy manage script
    ansible.builtin.copy:
      src: manage.sh
      dest: /home/manage.sh
  - name: Copy mailtrap token
    ansible.builtin.copy:
      content: "{{ lookup('community.sops.sops', 'mailtrap_token.enc.txt') }}"
      dest: /home/mailtrap_token.txt
